### ISSUE TITLE
racusum_arl_mc incorrectly testing the number of columns

### ISSUE THREAD

**Issue by mcshaz** [wittenberg/vlad#2]
Thank you for writing this.

When following the example `Supplemental material: Risk-adjusted CUSUM charts under model error` the code is included beginning line 319:

```
pmix <- data.frame(h=N1/sum(N1), p1=P, p2=P)
LLlarge <- racusum_arl_mc(pmix, QA, 1, hS, scaling=1e4, rounding="p", method="Toep")
```

pmix is indeed a data frame with the 3 columns specified (60 obs), but the `racusum_arl_mc` function returns

> Error in racusum_arl_mc(pmix, QA, 1, hS, scaling = 10000, rounding = "p",  : 
  1 assertions failed:
> * Variable 'pmix': Must have exactly 3 cols, but has 1 cols.

That is to say however the function is asserting the first argument has 3 columns seems to be doing this incorrectly.

**Comment by wittenberg** [comment]
During the development of the package, the order of standard arguments within the function has changed from `racusum_arl_mc(pmix, RA, RQ, h, scaling, rounding, method)` to `racusum_arl_mc(h, pmix, RA, RQ, scaling, rounding, method)`. Now, the first argument of the function is the control limit `h` instead of the patient mix `pmix`. 
You can account for this in your sample code `racusum_arl_mc(pmix, QA, 1, hS, scaling=1e4, rounding="p", method="Toep")` by doing the following:
1. reorder arguments to match the standard arguments of the function
`racusum_arl_mc(hS, pmix, QA, 1, scaling=1e4, rounding="p", method="Toep")`
2. assign function arguments with the `=` operator
`racusum_arl_mc(pmix=pmix, RA=QA, RQ=1, h=hS, scaling=1e4, rounding="p", method="Toep")`

**Comment by mcshaz** [comment]
I see now - thank you for pointing this out. 

The readme.md points to the example file on the journal publishers website (https://onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1002%2Fsim.8104&file=SIM_8104-Supp-0001-Supplemental-material-SIM-18-0571.R). I'll submit a pull request where this code is moved to within the GitHub repository so it can be kept in line with the API, and the relevant changes made to the example file.
